//datos de frases celebres
export const frases = [
    "\"Sócrates\": La vida no examinada no merece ser vivida.",
    "\"Aristóteles\": La felicidad depende de nosotros mismos.",
    "\"Descartes\": Pienso, luego existo.",
    "\"Nietzsche\": Lo que no nos mata nos hace más fuertes.",
    "\"Kant\": La razón es el origen de todo conocimiento.",
    "\"Platón\": El conocimiento verdadero es saber que no sabes nada.",
    "\"Confucio\": La mayor gloria no es nunca caer, sino levantarse siempre.",
    "\"Heráclito\": No puedes bañarte dos veces en el mismo río.",
    "\"Epicuro\": No es tanto el ayudar a nuestros amigos como el hacerlo con placer lo que nos hace felices.",
    "\"Séneca\": La felicidad es no necesitarla.",
    "\"Cicerón\": Si tienes un jardín y una biblioteca, tienes todo lo que necesitas.",
    "\"Sófocles\": La vida más dulce es no pensar en nada.",
    "\"María Zambrano\": Filosofar es encontrar argumentos para hacer llevadero el mal proceder de la razón.",
    "\"Simone de Beauvoir\": No se nace mujer: se llega a serlo.",
    "\"Jean-Paul Sartre\": El hombre está condenado a ser libre.",
    "\"Bertrand Russell\": El problema con el mundo es que los estúpidos están seguros de todo y los inteligentes están llenos de dudas.",
    "\"Hannah Arendt\": La pluralidad es la ley de la Tierra.",
    "\"Michel Foucault\": El conocimiento es poder.",
    "\"Lao Tse\": El viaje de mil millas comienza con un paso.",
    "\"Albert Camus\": El verdadero generoso es el que lo da todo, incluso la vida.",
    "\"Friedrich Engels\": La historia de todas las sociedades hasta la fecha es la historia de la lucha de clases.",
    "\"Marx\": La religión es el opio del pueblo.",
    "\"John Locke\": Donde no hay ley, no hay libertad.",
    "\"Ralph Waldo Emerson\": No vayas a donde el camino te lleve, ve donde no hay camino y deja un rastro.",
    "\"David Hume\": La razón es, y solo debe ser, esclava de las pasiones.",
    "\"William James\": El arte de ser sabio es el arte de saber qué pasar por alto.",
    "\"Henry David Thoreau\": Lo que un hombre piensa de sí mismo, esto es lo que determina, o más bien indica, su destino.",
    "\"Arthur Schopenhauer\": La vida es un negocio que no cubre ni sus costos.",
    "\"Ayn Rand\": La pregunta no es quién me va a dejar; es quién me va a detener.",
    "\"Immanuel Kant\": La moralidad no es la doctrina de cómo hacernos felices, sino de cómo debemos llegar a ser dignos de la felicidad.",
    "\"Confucio\": No importa lo lento que vayas, siempre y cuando no te detengas.",
    "\"Blaise Pascal\": El corazón tiene razones que la razón desconoce.",
    "\"Ludwig Wittgenstein\": Los límites de mi lenguaje son los límites de mi mundo.",
    "\"Mahatma Gandhi\": Sé el cambio que quieres ver en el mundo."
];

// datos de libros recomendados
export const libros = [
    "\"Sapiens\": Una fascinante exploración de la historia humana, desde el origen hasta el futuro, ofreciendo profundas reflexiones sobre nuestra especie.",
    "\"Mil Cerebros\": Desentraña el funcionamiento del cerebro, proponiendo una teoría revolucionaria sobre cómo pensamos y percibimos el mundo.",
    "\"El Universo de la Nada\": Investiga cómo el universo surgió de la nada, desafiando nuestras creencias sobre la existencia y la realidad.",
    "\"Amplitud\": Examina cómo las organizaciones y las personas pueden prosperar en un mundo interconectado, enfatizando la importancia de la adaptabilidad.",
    "\"Meditaciones\": Reflexiones filosóficas del emperador Marco Aurelio, ofreciendo sabiduría atemporal sobre la vida, la virtud y la serenidad.",
    "\"Una Breve Historia de Casi Todo\": Un viaje a través del tiempo y el espacio, desentrañando los misterios del universo con humor y claridad.",
    "\"El Aleph\": Colección de cuentos de Borges, explorando infinitos, realidades paralelas y lo desconocido, con una prosa exquisita y profunda.",
    "\"Cien Años de Soledad\": Gabriel García Márquez narra la historia épica de la familia Buendía en el ficticio pueblo de Macondo.",
    "\"El Hombre en Busca de Sentido\": Viktor Frankl comparte sus experiencias en los campos de concentración nazis y su teoría de la logoterapia.",
    "\"1984\": George Orwell presenta una visión distópica del futuro, explorando temas de vigilancia y control totalitario.",
    "\"El Principito\": Antoine de Saint-Exupéry nos lleva a un viaje filosófico a través de los ojos de un niño y su visión del mundo.",
    "\"La Odisea\": Homero narra las aventuras épicas de Odiseo en su viaje de regreso a casa después de la guerra de Troya.",
    "\"Orgullo y Prejuicio\": Jane Austen explora las complejidades del amor y la sociedad a través de la historia de Elizabeth Bennet y Mr. Darcy.",
    "\"El Gran Gatsby\": F. Scott Fitzgerald ofrece una crítica de la sociedad americana de los años 20 a través de la vida de Jay Gatsby.",
    "\"Don Quijote de la Mancha\": Miguel de Cervantes presenta las aventuras del idealista Don Quijote y su escudero Sancho Panza.",
    "\"Matar a un Ruiseñor\": Harper Lee aborda temas de racismo e injusticia en el sur de Estados Unidos a través de los ojos de Scout Finch.",
    "\"Crimen y Castigo\": Fiódor Dostoyevski explora la mente atormentada de Raskolnikov después de cometer un asesinato.",
    "\"El Retrato de Dorian Gray\": Oscar Wilde nos lleva a la decadente vida de Dorian Gray, quien se mantiene joven mientras su retrato envejece.",
    "\"Ulises\": James Joyce reinventa la Odisea de Homero en la ciudad de Dublín, a través de la vida de Leopold Bloom.",
    "\"La Divina Comedia\": Dante Alighieri describe su viaje imaginario a través del Infierno, el Purgatorio y el Paraíso.",
    "\"Fausto\": Johann Wolfgang von Goethe relata la historia del Dr. Fausto, quien hace un pacto con el diablo a cambio de conocimiento ilimitado.",
    "\"En Busca del Tiempo Perdido\": Marcel Proust presenta una introspección profunda sobre la memoria y el tiempo.",
    "\"El Proceso\": Franz Kafka narra la historia de Joseph K., quien es arrestado y procesado por un crimen que desconoce.",
    "\"Las Mil y Una Noches\": Una colección de cuentos árabes clásicos, narrados por Scheherazade para aplazar su ejecución.",
    "\"El Nombre de la Rosa\": Umberto Eco mezcla misterio, historia y teología en una abadía medieval donde ocurren una serie de asesinatos.",
    "\"La Metamorfosis\": Franz Kafka narra la surrealista transformación de Gregorio Samsa en un insecto gigante y su impacto en su vida y familia.",
    "\"Rayuela\": Julio Cortázar crea una novela experimental donde el lector puede elegir el orden de los capítulos.",
    "\"El Señor de los Anillos\": J.R.R. Tolkien nos lleva al mundo de la Tierra Media y la lucha épica contra el mal.",
    "\"Moby-Dick\": Herman Melville relata la obsesiva búsqueda del capitán Ahab por la gran ballena blanca.",
    "\"La Montaña Mágica\": Thomas Mann explora las tensiones culturales y filosóficas en un sanatorio de los Alpes antes de la Primera Guerra Mundial."
];

//datos de chistes
export const chistes = [
    "\"Chiste 1\": ¿Por qué los pájaros no usan Facebook? Porque ya tienen Twitter.",
    "\"Chiste 2\": ¿Qué le dice una iguana a su hermana gemela? Somos iguanitas.",
    "\"Chiste 3\": ¿Por qué los esqueletos no pelean entre ellos? Porque no tienen agallas.",
    "\"Chiste 4\": ¿Qué hace una abeja en el gimnasio? Zum-ba.",
    "\"Chiste 5\": ¿Cómo organizas una fiesta en el espacio? ¡Planeta!",
    "\"Chiste 6\": ¿Qué hace una vaca con los ojos cerrados? Leche concentrada.",
    "\"Chiste 7\": ¿Por qué las computadoras no pueden nadar? Porque tienen un ratón dentro.",
    "\"Chiste 8\": ¿Qué hace un perro con un taladro? Taladrando.",
    "\"Chiste 9\": ¿Cuál es el colmo de Aladdín? Tener mal genio.",
    "\"Chiste 10\": ¿Qué le dice una piedra a otra piedra? ¡Qué dura es la vida!",
    "\"Chiste 11\": ¿Por qué el libro de matemáticas está triste? Porque tiene demasiados problemas.",
    "\"Chiste 12\": ¿Cómo se despiden los químicos? Ácido un placer.",
    "\"Chiste 13\": ¿Por qué el tomate no toma café? Porque ya toma ketchup.",
    "\"Chiste 14\": ¿Qué hace una abeja en el gimnasio? ¡Zum-ba!",
    "\"Chiste 15\": ¿Por qué los peces no van a la escuela? Porque están en el mar-teléfono.",
    "\"Chiste 16\": ¿Qué le dice una iguana a su hermana gemela? Somos iguanitas.",
    "\"Chiste 17\": ¿Qué hace una abeja en el gimnasio? Zum-ba.",
    "\"Chiste 18\": ¿Qué le dice una iguana a su hermana gemela? Somos iguanitas.",
    "\"Chiste 19\": ¿Por qué los esqueletos no pelean entre ellos? Porque no tienen agallas.",
    "\"Chiste 20\": ¿Qué hace una abeja en el gimnasio? Zum-ba.",
    "\"Chiste 21\": ¿Cómo organizas una fiesta en el espacio? ¡Planeta!",
    "\"Chiste 22\": ¿Qué hace una vaca con los ojos cerrados? Leche concentrada.",
    "\"Chiste 23\": ¿Por qué las computadoras no pueden nadar? Porque tienen un ratón dentro.",
    "\"Chiste 24\": ¿Qué hace un perro con un taladro? Taladrando.",
    "\"Chiste 25\": ¿Cuál es el colmo de Aladdín? Tener mal genio.",
    "\"Chiste 26\": ¿Qué le dice una piedra a otra piedra? ¡Qué dura es la vida!",
    "\"Chiste 27\": ¿Por qué el libro de matemáticas está triste? Porque tiene demasiados problemas.",
    "\"Chiste 28\": ¿Cómo se despiden los químicos? Ácido un placer.",
    "\"Chiste 29\": ¿Por qué las avestruces no corren carreras? Porque siempre llegan con el pico suelto.",
    "\"Chiste 30\": ¿Cómo se llama el campeón de buceo japonés? Tokofondo.",
    "\"Chiste 31\": ¿Cuál es el colmo de un electricista? Perder el hilo de la conversación.",
    "\"Chiste 32\": ¿Qué pasa si tiras un pato al agua? Nada.",
    "\"Chiste 33\": ¿Cómo se llama un perro que hace magia? ¡Un labracadabrador!",
    "\"Chiste 34\": ¿Por qué los pájaros no usan Facebook? Porque ya tienen Twitter.",
    "\"Chiste 35\": ¿Qué le dice una iguana a su hermana gemela? Somos iguanitas.",
    "\"Chiste 36\": ¿Qué hace una abeja en el gimnasio? Zum-ba.",
    "\"Chiste 37\": ¿Qué le dice una iguana a su hermana gemela? Somos iguanitas.",
    "\"Chiste 38\": ¿Por qué los esqueletos no pelean entre ellos? Porque no tienen agallas.",
    "\"Chiste 39\": ¿Qué hace una abeja en el gimnasio? Zum-ba.",
    "\"Chiste 40\": ¿Cómo organizas una fiesta en el espacio? ¡Planeta!"
];

//datos de discos
export const reseñasDeDiscos = [
    "\"Kind of Blue\": Una obra maestra del jazz de Miles Davis, explorando la improvisación modal con un sonido único y evocador.",
    "\"A Love Supreme\": John Coltrane fusiona espiritualidad y música, creando un álbum trascendental y profundamente emotivo, lleno de intensidad y devoción.",
    "\"Djesse 3\": Jacob Collier despliega su genio musical en un álbum ecléctico, fusionando géneros con maestría y creatividad desbordante.",
    "\"We Live Here\": Pat Metheny Group ofrece una mezcla única de jazz, funk y world music, creando paisajes sonoros envolventes y sofisticados.",
    "\"Dark Side of the Moon\": Pink Floyd crea una obra atemporal, explorando temas profundos con innovaciones sonoras y producción impecable.",
    "\"Abbey Road\": The Beatles se despiden con un álbum icónico, lleno de armonías perfectas, melodías inolvidables y experimentación sonora.",
    "\"Innuendo\": Queen muestra su diversidad musical en un álbum poderoso y emotivo, lleno de mensajes profundos y momentos épicos.",
    "\"Off the Wall\": Michael Jackson fusiona disco, pop y funk en un álbum vibrante, estableciendo su legado como el Rey del Pop.",
    "\"El Amor Después del Amor\": Fito Páez ofrece una oda al amor y la vida en un álbum cargado de pasión, melancolía y genialidad lírica.",
    "\"Blue\": Joni Mitchell crea una obra maestra introspectiva y emocional, explorando los altibajos del amor y la vida.",
    "\"Rumours\": Fleetwood Mac ofrece un álbum icónico lleno de armonías perfectas y letras introspectivas sobre el amor y el desamor.",
    "\"Hotel California\": The Eagles exploran el lado oscuro del sueño americano con melodías inolvidables y letras poéticas.",
    "\"Thriller\": Michael Jackson establece un nuevo estándar en el pop, combinando géneros con maestría en un álbum lleno de éxitos.",
    "\"The Wall\": Pink Floyd presenta una ópera rock épica, explorando temas de aislamiento y autoritarismo con una producción impresionante.",
    "\"Graceland\": Paul Simon fusiona el pop con la música tradicional africana, creando un álbum vibrante y culturalmente significativo.",
    "\"Back to Black\": Amy Winehouse ofrece un álbum profundamente personal y emocional, fusionando el soul clásico con una modernidad cruda.",
    "\"Legend\": Bob Marley & The Wailers presentan una colección de sus mayores éxitos, difundiendo mensajes de amor y unidad a través del reggae.",
    "\"The Beatles (White Album)\": The Beatles ofrecen una colección ecléctica y experimental, explorando una amplia gama de estilos musicales.",
    "\"Purple Rain\": Prince fusiona rock, funk y pop en un álbum icónico que destaca su genio musical y su impacto cultural duradero.",
    "\"Pet Sounds\": The Beach Boys crean un álbum revolucionario con complejas armonías y arreglos innovadores que redefinen el pop.",
    "\"Born to Run\": Bruce Springsteen ofrece una epopeya rockera llena de energía y pasión, capturando la esencia del sueño americano.",
    "\"Nevermind\": Nirvana redefine el grunge y el rock alternativo con un álbum crudo y poderoso, liderado por la voz intensa de Kurt Cobain.",
    "\"The Rise and Fall of Ziggy Stardust and the Spiders from Mars\": David Bowie introduce su alter ego Ziggy Stardust en un álbum conceptual y visionario.",
    "\"Songs in the Key of Life\": Stevie Wonder ofrece una obra maestra del soul y el funk, llena de mensajes positivos y arreglos complejos.",
    "\"What's Going On\": Marvin Gaye explora temas sociales y políticos con una sensibilidad soul única, creando un álbum profundamente emotivo.",
    "\"London Calling\": The Clash fusiona punk, reggae y rock en un álbum rebelde y diverso que aborda temas sociales y políticos.",
    "\"Blue Train\": John Coltrane presenta una obra maestra del jazz, combinando su virtuosismo con composiciones innovadoras y emotivas.",
    "\"Exile on Main St.\": The Rolling Stones ofrecen un álbum crudo y variado, explorando el blues, el rock y el country con una producción áspera y auténtica.",
    "\"Blood on the Tracks\": Bob Dylan ofrece un álbum profundamente personal y emotivo, con letras introspectivas sobre el amor y la pérdida.",
    "\"Automatic for the People\": R.E.M. presenta un álbum introspectivo y melódico, explorando temas de mortalidad y humanidad con gran sensibilidad.",
    "\"The Joshua Tree\": U2 fusiona el rock con sonidos atmosféricos, creando un álbum épico que aborda temas de espiritualidad y justicia social."
];

//datos de microcuentos
export const microcuentos = [
    "\"Augusto Monterroso\": Cuando despertó, el dinosaurio todavía estaba allí.",
    "\"Franz Kafka\": Al pasar frente a la casa, miró hacia adentro. El interior era sencillo. Todo lo demás es incomprensible.",
    "\"Ana María Shua\": Cuando tocó su rostro, descubrió que estaba tocando una máscara. Entonces comprendió que todas lo eran.",
    "\"Julio Cortázar\": En la pulpería, después de tres noches de lluvia, se escuchó el trote de un caballo que no llegaba nunca.",
    "\"Luis Mateo Díez\": La vida es una burbuja a punto de estallar. Sin embargo, la burbuja no estalla.",
    "\"José Luis Borges\": En la vida de todo hombre hay dos grandes días: el día en que nace y el día en que descubre para qué ha nacido.",
    "\"Italo Calvino\": Estaba decidido a encontrar un diamante en la playa de arena. Al atardecer, lo halló, en su propio corazón.",
    "\"Javier Tomeo\": En la última página de su diario escribió: ‘Mañana empiezo a vivir’. No llegó.",
    "\"Félix J. Palma\": Sabía que no podía mirarla y sin embargo, no podía apartar la vista. Ella tampoco, aunque estaba ciega.",
    "\"Juan José Arreola\": Y Dios le preguntó: ‘¿Qué haces aquí?’. El hombre respondió: ‘Vengo a que me devuelvas el costado’.",
    "\"Margaret Atwood\": Nunca más le temió a la oscuridad, pues sabía que el monstruo estaba dentro de ella.",
    "\"Leonardo Da Vinci\": Por mucho que volase el ave de oro, jamás se alejó de su jaula.",
    "\"Ángel Olgoso\": El eco respondía antes de que nadie hablase. Se dieron cuenta de que la montaña estaba viva.",
    "\"Quim Monzó\": Llovió todo el día y toda la noche, y a la mañana siguiente el pueblo ya no estaba.",
    "\"Juan Rulfo\": Las palabras que no dije me hicieron un nido en la garganta. Ahí viven todavía.",
    "\"Ana María Matute\": El espejo no reflejaba a quien lo miraba, sino a quien soñaba.",
    "\"Mario Benedetti\": El miedo del escarabajo es ser grande. El miedo del hombre es ser pequeño.",
    "\"H. P. Lovecraft\": El hombre que nunca había visto un espejo no supo que era él quien lo miraba con odio.",
    "\"Gabriel García Márquez\": En cien años de olvido, un hombre volvió a encontrar su sombra y no la reconoció.",
    "\"Horacio Quiroga\": La última gota de lluvia golpeó el suelo, y el silencio se volvió tan profundo que dolía.",
    "\"Isabel Allende\": Cuando ella cerró el libro, él se quedó atrapado en sus páginas para siempre.",
    "\"Frederico García Lorca\": En el rincón más oscuro del bosque, una luciérnaga creía ser la luna.",
    "\"Oscar Wilde\": La rosa sintió celos de la sangre cuando el poeta se cortó escribiendo sobre ella.",
    "\"Anton Chejov\": Las estrellas no le respondían porque ya sabían que él no escucharía.",
    "\"Edgar Allan Poe\": La sombra que lo seguía no era suya, sino del ser que habitaba en sus pensamientos.",
    "\"Ray Bradbury\": El viento soplaba, pero esta vez no movía nada, porque ya no quedaba nada que mover.",
    "\"Juan Bosch\": Un ladrón le robó la voz, y cuando quiso pedir ayuda, solo su eco respondió.",
    "\"Charles Dickens\": Dejó la llave en la puerta, pero su libertad nunca se asomó.",
    "\"Mark Twain\": Había tantas nubes que el cielo dejó de existir, y la lluvia nunca supo de dónde caía.",
    "\"Haruki Murakami\": Cuando despertó, encontró el mundo desordenado y comprendió que era su reflejo."
];
